### ISSUE TITLE
Add capital and latitude-longitude data

### ISSUE THREAD

**Issue by jhollway** [globalgov/manystates#50]

**Comment by BBieri** [comment]
This is already present in the `{cshapes}` data. Do we need both sources?

**Comment by jhollway** [comment]
Does `{cshapes}` have all of this data, also for historical capitals/capitals of historical states?

**Comment by BBieri** [comment]
Yes, simply use `import_cshapes(date = "1900-01-01")` with the corresponding date and you'll get a data frame containing not only the shapes but also the coordinates of the capital of the (historical) country. If you're looking for data on distances, use the `import_distmatrix(date = "1900-01-01", type = "capdist")` function or the `import_distlist()` function with the corresponding date.

**Comment by jhollway** [comment]
Please make sure that _all_ of this data is included before we dispose of the material added.

**Comment by jaeltan** [comment]
Some of the capitals and states are not included in `{cshapes}` so I'm adding the data into `{manystates}`
