### ISSUE TITLE
Go through manystates

### ISSUE THREAD

**Issue by jaeltan** [globalgov/manystates#59]
Check if the functions to import data eg. V-dem and if the data is up-to-date

**Comment by jaeltan** [comment]
I've gone through the manystates package, looking through the datasets and checking the functions. The `import_vdem/vparty/cshapes` functions are now up-to-date, and there are HUGGO datasets in the `states`, `contiguity`, and `leaders` databases. In the leaders database, the HUGGO dataset contains only the rows in the Archigos dataset that Bernhard made corrections. In the states and contiguity databases, the HUGGO datasets are handcoded datasets from previous work by @jhollway. We could expand the HUGGO datasets by checking for and resolving conflicts for the start/end dates of states as we are doing for agreements/memberships data in manyenviron and manytrade, but I think this is not a priority for the project at the moment.

**Comment by henriquesposito** [comment]
Thank you for all the work @jaeltan ! I will start working on the vignette for the package so that we can open a PR there soonish!
