### ISSUE TITLE
ICOW datasets for qStates

### ISSUE THREAD

**Issue by henriquesposito** [globalgov/manystates#9]
We should look into whether it would be interesting to add the ICOW dataset on state names and changes (http://www.paulhensel.org/icownames.html) as well as their dataset on colonial history (http://www.paulhensel.org/icowcol.html) to the qStates package.

**Comment by BBieri** [comment]
## Update 28th Dec. 2020:

[x]  First, write a very short description of the datasets mentioned above focusing on what do they look at, how they were coded by whom and when (this is meant to be just a very very brief overview).

[x]  Second, identify their licenses. *We will need to email Paul Hensel for permission to redistribute the data in our package*

[x]  Take a look at the raw data folder already in qStates, how do you think these datasets can be incorporated into the package? What do we gain (or loose) from incorporating them? (Just a short and concise answer)

[ ] Fourth, download the datasets and attempt to collect and correct the data the best you can using the qData package tools. Try and make them as consistent as you can with the other datasets already in (you should find a few short scripts for references within the data-raw folder). (*in progress, data is downloaded and will be cleaned tomorrow*)
